CREATE TABLE IF NOT EXISTS clientes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  email TEXT,
  telefone TEXT
);

CREATE TABLE IF NOT EXISTS produtos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  preco REAL NOT NULL,
  quantidade INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS vendedores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  email TEXT,
  comissao REAL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS movimentacoes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tipo TEXT NOT NULL,
  quantidade INTEGER NOT NULL,
  data TEXT NOT NULL,
  cliente_id INTEGER NOT NULL,
  produto_id INTEGER NOT NULL,
  vendedor_id INTEGER NOT NULL,
  FOREIGN KEY (cliente_id) REFERENCES clientes (id),
  FOREIGN KEY (produto_id) REFERENCES produtos (id),
  FOREIGN KEY (vendedor_id) REFERENCES vendedores (id)
);
